version: "2"

services:
  mongo:
    image: mongo:3.2
    container_name: mongo
    command: --smallfiles
    ports:
      - "27017:27017"
    volumes:
      - db-volume:/data/db
volumes:
  db-volume:
  swipe-www:
