version: "2"

services:
  swipe:
    image: danedmunds/swipe:latest
    restart: on-failure
    environment:
      - CONNECTIONSTRING=mongodb://mongo:27017/swipe
      - PORT=3000
    ports:
      - "80:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:3.2
    container_name: mongo
    command: --smallfiles
